### PR TITLE
Update package to reference .Net Core 2 and .Net Standard 2

### PR DESCRIPTION
**Pull request by bozau**
I've updated the package code to reference .Net Core 2 and .Net Standard 2 libraries for use in developer projects for .Net Core 2.

Due to the IdentityBuilder unable to be referenced/found when referring to .Net Core 1.1 packages when building the AddIdentity service;
`            services.AddIdentity< ApplicationUser, Neo4jIdentityRole >()
                    .UseNeo4jDataStoreAdapter()
                    .AddDefaultTokenProviders();`

I've also added the attribute `TwoFactorEnabled` to the `IdentityUser` file as .Net Core 2 MVC projects have this referenced by default as part of their authentication template. But, work will need to be done to make the package fully compatible.

### CODE REVIEW

**Comment by cskardon** [comment]
Hey @aaron-bozit ! Thank you for this - it looks good to me, I have a quick question,. You write:

>  But, work will need to be done to make the package fully compatible.

What work needs to be done? If I commit this, will it work - or does it go into a broken state?

Thanks again!

Chris

**Comment by bozau** [comment]
@cskardon Sorry about that, that line is a bit ambiguous, I mean that work would still need to be done to make it work with Two Factor and Social Logins.

I've made it into a Nuget package to test and referenced it into a .Net Core 2.0 project and it is working fine without the two features talked about above.

**Comment by cskardon** [comment]
That's the kind of ambiguity I like! One that's easy to resolve - thank you!

**Comment by cskardon** [comment]
PS - what're you feelings RE shifting it to release rather than -pre?

**Comment by bozau** [comment]
Um, you could, it doesn't have Two Factor or Social logins (I'm looking into the social logins part at the moment).

Up to you.

**Comment by cskardon** [comment]
Sticking with `pre` for now, it's in nuget now, once I get appveyor setup correctly - I'll get that auto building which should speed up this whole process ;)

**Pull request merged**
